"""phase3c profile google oauth otp

Revision ID: 20e0dbfaef7e
Revises: 64e2bd7bbd16
Create Date: 2026-09-11 21:54:45.122251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e0dbfaef7e'
down_revision: Union[str, Sequence[str], None] = '64e2bd7bbd16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='Cloudinary CDN URL'))
    op.add_column('users', sa.Column('bio', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=100), nullable=True, comment='Google subject ID; present on OAuth-created or linked accounts'))
    op.add_column('users', sa.Column('reset_otp_hash', sa.String(length=255), nullable=True, comment='bcrypt hash of the 6-digit OTP'))
    op.add_column('users', sa.Column('reset_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # server_default is required here, not just the model's Python-side
    # default=0 — this table already has rows (50 in dev), and Postgres
    # rejects adding a NOT NULL column with no default when the table is
    # non-empty. Dropped again after backfilling so future inserts still go
    # through the ORM default rather than relying on a server default forever.
    op.add_column('users', sa.Column('reset_otp_attempts', sa.Integer(), nullable=False, server_default='0', comment='Failed OTP attempts this reset cycle; auto-expire after 3'))
    op.alter_column('users', 'reset_otp_attempts', server_default=None)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt hash; NULL for legacy anonymous users or Google-only accounts',
               existing_comment='bcrypt hash; NULL for legacy anonymous users',
               existing_nullable=True)
    op.create_unique_constraint('uq_users_google_id', 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_google_id', 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt hash; NULL for legacy anonymous users',
               existing_comment='bcrypt hash; NULL for legacy anonymous users or Google-only accounts',
               existing_nullable=True)
    op.drop_column('users', 'reset_otp_attempts')
    op.drop_column('users', 'reset_otp_expires_at')
    op.drop_column('users', 'reset_otp_hash')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
