"""phase5 clarity scores

Revision ID: 4a0ad18fe864
Revises: 84b822139414
Create Date: 2026-10-05 14:12:01.116341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0ad18fe864'
down_revision: Union[str, Sequence[str], None] = '84b822139414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clarity_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False, comment='0-100 estimate from speech-recognition confidence'),
    sa.Column('word_level', sa.Boolean(), nullable=False, comment='False = rough estimate from segment confidence only (no per-word confidences)'),
    sa.Column('avg_word_confidence', sa.Float(), nullable=True),
    sa.Column('avg_logprob', sa.Float(), nullable=False),
    sa.Column('words_scored', sa.Integer(), nullable=False),
    sa.Column('unclear_words', sa.JSON(), nullable=False, comment='[{word, probability, start, end}] — the least clearly recognised words'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_clarity_scores_conversation_id'), 'clarity_scores', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_clarity_scores_user_id'), 'clarity_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clarity_scores_user_id'), table_name='clarity_scores')
    op.drop_index(op.f('ix_clarity_scores_conversation_id'), table_name='clarity_scores')
    op.drop_table('clarity_scores')
    # ### end Alembic commands ###
