"""phase9 weaknesses and session focus

Revision ID: 6bc175274e82
Revises: 8213f226af14
Create Date: 2026-10-05 14:45:53.980575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc175274e82'
down_revision: Union[str, Sequence[str], None] = '8213f226af14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_weaknesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('subtype', sa.String(length=50), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False, comment='all-time mistakes of this kind'),
    sa.Column('recent_count', sa.Integer(), nullable=False, comment='in the last 30 days'),
    sa.Column('previous_count', sa.Integer(), nullable=False, comment='in the 30 days before that'),
    sa.Column('sessions_seen', sa.Integer(), nullable=False, comment='distinct sessions it appeared in'),
    sa.Column('priority', sa.Float(), nullable=False, comment='ranking weight: recent mistakes count most'),
    sa.Column('trend', sa.String(length=12), nullable=False, comment='new | improving | stable | worsening'),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'subtype', name='uq_user_weakness')
    )
    op.create_index(op.f('ix_user_weaknesses_user_id'), 'user_weaknesses', ['user_id'], unique=False)
    op.add_column('conversations', sa.Column('focus', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'focus')
    op.drop_index(op.f('ix_user_weaknesses_user_id'), table_name='user_weaknesses')
    op.drop_table('user_weaknesses')
    # ### end Alembic commands ###
