"""initial_schema

Revision ID: 743b55240af5
Revises: 
Create Date: 2026-09-08 23:15:01.380275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743b55240af5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preferred_voice', sa.String(length=50), nullable=False, comment='One of: amy, alan, ryan, lessac'),
    sa.Column('preferred_style', sa.String(length=50), nullable=False, comment='One of: standard, australian, irish, scouse, caribbean, pirate'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scenario', sa.String(length=50), nullable=False, comment='One of: casual, interview, travel, debate, professional, university'),
    sa.Column('style', sa.String(length=50), nullable=False, comment='Speaking style / English variety preset'),
    sa.Column('voice', sa.String(length=50), nullable=False, comment='Piper voice ID'),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False, comment="'user' or 'assistant'"),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('audio_duration_seconds', sa.Float(), nullable=True),
    sa.Column('word_timestamps_json', sa.Text(), nullable=True, comment='JSON: [{word, start, end, probability}, ...] from faster-whisper'),
    sa.Column('whisper_avg_logprob', sa.Float(), nullable=True, comment='Average log-probability from Whisper — used as pronunciation proxy'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('conversations')
    op.drop_table('users')
    # ### end Alembic commands ###
