"""phase7 session reports

Revision ID: 8213f226af14
Revises: 98e7decef5f7
Create Date: 2026-10-05 14:34:07.956063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8213f226af14'
down_revision: Union[str, Sequence[str], None] = '98e7decef5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scoring_version', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('grammar_score', sa.Integer(), nullable=True),
    sa.Column('vocabulary_score', sa.Integer(), nullable=True),
    sa.Column('fluency_score', sa.Integer(), nullable=True),
    sa.Column('clarity_score', sa.Integer(), nullable=True),
    sa.Column('naturalness_score', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('improvements', sa.JSON(), nullable=False),
    sa.Column('top_errors', sa.JSON(), nullable=False, comment='[{category, subtype, label, count, example_original, example_correction}], most frequent first'),
    sa.Column('practice_words', sa.JSON(), nullable=False, comment='words the recogniser struggled with, most often first'),
    sa.Column('summary', sa.Text(), nullable=True, comment="a short coach's note; NULL if it couldn't be written"),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('mistake_count', sa.Integer(), nullable=False),
    sa.Column('suggestion_count', sa.Integer(), nullable=False),
    sa.Column('praise_count', sa.Integer(), nullable=False),
    sa.Column('avg_wpm', sa.Float(), nullable=True),
    sa.Column('filler_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index(op.f('ix_session_reports_user_id'), 'session_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_reports_user_id'), table_name='session_reports')
    op.drop_table('session_reports')
    # ### end Alembic commands ###
