"""phase4 fluency scores and events

Revision ID: 84b822139414
Revises: fbff332a6424
Create Date: 2026-10-05 14:04:35.711389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b822139414'
down_revision: Union[str, Sequence[str], None] = 'fbff332a6424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fluency_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False, comment='0-100; see services/fluency.compute_score'),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('speech_seconds', sa.Float(), nullable=False, comment='first word start -> last word end'),
    sa.Column('wpm', sa.Float(), nullable=True, comment='NULL when there was too little speech to say'),
    sa.Column('articulation_wpm', sa.Float(), nullable=True, comment='speaking rate with pauses removed'),
    sa.Column('pause_count', sa.Integer(), nullable=False),
    sa.Column('long_pause_count', sa.Integer(), nullable=False),
    sa.Column('total_pause_seconds', sa.Float(), nullable=False),
    sa.Column('longest_pause_seconds', sa.Float(), nullable=False),
    sa.Column('filler_count', sa.Integer(), nullable=False),
    sa.Column('filler_breakdown', sa.JSON(), nullable=False, comment='e.g. {"um": 3, "you know": 1}'),
    sa.Column('repetition_count', sa.Integer(), nullable=False),
    sa.Column('hesitations_tracked', sa.Boolean(), nullable=False, comment="False when the recogniser drops um/uh, so a filler count of 0 means 'couldn't hear them'"),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_fluency_scores_conversation_id'), 'fluency_scores', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_fluency_scores_user_id'), 'fluency_scores', ['user_id'], unique=False)
    op.create_table('fluency_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fluency_score_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False, comment='pause | long_pause | filler | repetition'),
    sa.Column('text', sa.String(length=100), nullable=False, comment='the filler/repeated word, or the pause length'),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fluency_score_id'], ['fluency_scores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fluency_events_fluency_score_id'), 'fluency_events', ['fluency_score_id'], unique=False)
    op.create_index(op.f('ix_fluency_events_user_id'), 'fluency_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fluency_events_user_id'), table_name='fluency_events')
    op.drop_index(op.f('ix_fluency_events_fluency_score_id'), table_name='fluency_events')
    op.drop_table('fluency_events')
    op.drop_index(op.f('ix_fluency_scores_user_id'), table_name='fluency_scores')
    op.drop_index(op.f('ix_fluency_scores_conversation_id'), table_name='fluency_scores')
    op.drop_table('fluency_scores')
    # ### end Alembic commands ###
