"""phase6 correction is_positive

Revision ID: 98e7decef5f7
Revises: 4a0ad18fe864
Create Date: 2026-10-05 14:17:33.673521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e7decef5f7'
down_revision: Union[str, Sequence[str], None] = '4a0ad18fe864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corrections', sa.Column('is_positive', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corrections', 'is_positive')
    # ### end Alembic commands ###
