"""phase3d email verification token version analysis status

Revision ID: fbff332a6424
Revises: 20e0dbfaef7e
Create Date: 2026-10-05 13:26:45.555039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbff332a6424'
down_revision: Union[str, Sequence[str], None] = '20e0dbfaef7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'scenario',
               existing_type=sa.VARCHAR(length=50),
               comment='A key of personalities.SCENARIOS',
               existing_comment='One of: casual, interview, travel, debate, professional, university',
               existing_nullable=False)
    op.alter_column('conversations', 'voice',
               existing_type=sa.VARCHAR(length=50),
               comment='Piper voice / companion id (personalities.VOICES)',
               existing_comment='Piper voice ID',
               existing_nullable=False)
    op.add_column('messages', sa.Column('analysis_status', sa.String(length=10), server_default=sa.text("'done'"), nullable=False))
    op.add_column('users', sa.Column('reset_otp_sent_at', sa.DateTime(timezone=True), nullable=True, comment='When the last reset code was issued; enforces a resend cooldown'))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True once the owner has proven control of the email address'))
    op.add_column('users', sa.Column('verify_otp_hash', sa.String(length=255), nullable=True, comment='bcrypt hash of the signup / verify-email OTP'))
    op.add_column('users', sa.Column('verify_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('verify_otp_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('verify_otp_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False, comment='Embedded in JWTs; incrementing it revokes all existing tokens'))
    # Accounts linked to Google already had their email vouched for by Google.
    op.execute("UPDATE users SET email_verified = true WHERE google_id IS NOT NULL")
    op.alter_column('users', 'preferred_voice',
               existing_type=sa.VARCHAR(length=50),
               comment='A key of personalities.VOICES (companion id)',
               existing_comment='One of: amy, alan, ryan, lessac',
               existing_nullable=False)
    op.alter_column('users', 'preferred_style',
               existing_type=sa.VARCHAR(length=50),
               comment='A key of personalities.STYLES',
               existing_comment='One of: standard, australian, irish, scouse, caribbean, pirate',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'preferred_style',
               existing_type=sa.VARCHAR(length=50),
               comment='One of: standard, australian, irish, scouse, caribbean, pirate',
               existing_comment='A key of personalities.STYLES',
               existing_nullable=False)
    op.alter_column('users', 'preferred_voice',
               existing_type=sa.VARCHAR(length=50),
               comment='One of: amy, alan, ryan, lessac',
               existing_comment='A key of personalities.VOICES (companion id)',
               existing_nullable=False)
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'verify_otp_sent_at')
    op.drop_column('users', 'verify_otp_attempts')
    op.drop_column('users', 'verify_otp_expires_at')
    op.drop_column('users', 'verify_otp_hash')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'reset_otp_sent_at')
    op.drop_column('messages', 'analysis_status')
    op.alter_column('conversations', 'voice',
               existing_type=sa.VARCHAR(length=50),
               comment='Piper voice ID',
               existing_comment='Piper voice / companion id (personalities.VOICES)',
               existing_nullable=False)
    op.alter_column('conversations', 'scenario',
               existing_type=sa.VARCHAR(length=50),
               comment='One of: casual, interview, travel, debate, professional, university',
               existing_comment='A key of personalities.SCENARIOS',
               existing_nullable=False)
    # ### end Alembic commands ###
